version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: cs_redis
    ports:
      - "6379:6379"
    labels:
      - "name=redis"
      - "mode=standalone"
  mysql:
    container_name: cs_mysql
    image: mysql:8.0
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=1
      --default-time-zone='Asia/Seoul'
    environment:
      MYSQL_DATABASE: cs
      MYSQL_USER: mo-greene
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
